spring:
  cloud:
    gateway:
      routes:
      - id: managefactor
        uri: lb://managefactor
        predicates:
        - Path=/factor/**,/authenticate/
      - id: currencyconverter
        uri: lb://currencyconverter
        predicates:
        - Path=/convert/**